[package]
name = "vulkanrust"
version = "0.1.0"
edition = "2021"

[dependencies]
ash = "0.38.0"
ash-window = "0.13.0"
winit = { version = "0.29", features = ["rwh_06"] }
vk-mem = {path = "thirdparty/vk-mem-rs"}